# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/.github/actions/find"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/.github/actions/file"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/.github/actions/fix"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gh-cache/cache"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gh-cache/restore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/gh-cache/save"
    schedule:
      interval: "weekly"
